services:
    
  mongo:
    image: mongo:latest
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd
      - MONGO_INITDB_DATABASE=users           # ?
      volumes:
      - ./mongo-data:/data/db
      - ./mongodb_config:/data/configdb       # ?
      
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express    
    ports:
      - "8081:8081"
    restart: unless-stopped       
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=p4ssw0rd
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo   
      

